// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAccount = `-- name: GetAccount :one
SELECT id, parent_id, kind, name, commodity_code, closed
  FROM accounts WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.CommodityCode,
		&i.Closed,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :exec
INSERT INTO accounts (id, parent_id, kind, name, commodity_code, closed)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAccountParams struct {
	ID            pgtype.UUID
	ParentID      pgtype.UUID
	Kind          string
	Name          string
	CommodityCode *string
	Closed        bool
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.Exec(ctx, insertAccount,
		arg.ID,
		arg.ParentID,
		arg.Kind,
		arg.Name,
		arg.CommodityCode,
		arg.Closed,
	)
	return err
}

const listAccountSubtree = `-- name: ListAccountSubtree :many
WITH RECURSIVE subtree(id) AS (
    SELECT a.id FROM accounts a WHERE a.id = $1
    UNION ALL
    SELECT a.id FROM accounts a JOIN subtree s ON a.parent_id = s.id
)
SELECT s.id FROM subtree s ORDER BY s.id
`

func (q *Queries) ListAccountSubtree(ctx context.Context, id pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAccountSubtree, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, parent_id, kind, name, commodity_code, closed
  FROM accounts ORDER BY id
`

// The whole tree. Building a ledger.AccountTree needs every ancestor of every
// account it contains, and an account tree is tens to low hundreds of rows, so
// the whole set is the honest unit to read.
func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Kind,
			&i.Name,
			&i.CommodityCode,
			&i.Closed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
