// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmTOTP = `-- name: ConfirmTOTP :execrows
UPDATE user_totp
   SET confirmed_at = $2
 WHERE user_id = $1 AND confirmed_at IS NULL
`

type ConfirmTOTPParams struct {
	UserID      pgtype.UUID
	ConfirmedAt pgtype.Timestamptz
}

func (q *Queries) ConfirmTOTP(ctx context.Context, arg ConfirmTOTPParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmTOTP, arg.UserID, arg.ConfirmedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countCredentialedUsers = `-- name: CountCredentialedUsers :one
SELECT count(*) FROM users WHERE email IS NOT NULL
`

// Whether this instance has anybody yet. Used to decide what a registration
// form should offer, never to decide whether a registration may proceed —
// that answer would be stale the moment it was read.
func (q *Queries) CountCredentialedUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCredentialedUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnusedBackupCodes = `-- name: CountUnusedBackupCodes :one
SELECT count(*) FROM user_backup_codes WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) CountUnusedBackupCodes(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnusedBackupCodes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBackupCodes = `-- name: DeleteBackupCodes :execrows
DELETE FROM user_backup_codes WHERE user_id = $1
`

// Issuing a new set replaces the old one outright, spent codes included. A
// code from a previous set must not survive a regeneration: the person asked
// for a clean slate, usually because they think the old list leaked.
func (q *Queries) DeleteBackupCodes(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBackupCodes, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= $1
`

// Sweeping. A revoked session is kept until it would have expired anyway, so
// that "this session was revoked" remains answerable for as long as anyone
// might ask.
func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTOTP = `-- name: DeleteTOTP :execrows
DELETE FROM user_totp WHERE user_id = $1
`

func (q *Queries) DeleteTOTP(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTOTP, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCredentialsByEmail = `-- name: GetCredentialsByEmail :one
SELECT id, email, password_hash, password_changed_at, created_at
  FROM users
 WHERE lower(email) = lower($1::text)
`

type GetCredentialsByEmailRow struct {
	ID                pgtype.UUID
	Email             *string
	PasswordHash      *string
	PasswordChangedAt pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

// Case-insensitive, matching the users_email_key index expression exactly so
// the lookup uses it rather than scanning.
func (q *Queries) GetCredentialsByEmail(ctx context.Context, email string) (GetCredentialsByEmailRow, error) {
	row := q.db.QueryRow(ctx, getCredentialsByEmail, email)
	var i GetCredentialsByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCredentialsByID = `-- name: GetCredentialsByID :one
SELECT id, email, password_hash, password_changed_at, created_at
  FROM users
 WHERE id = $1
`

type GetCredentialsByIDRow struct {
	ID                pgtype.UUID
	Email             *string
	PasswordHash      *string
	PasswordChangedAt pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) GetCredentialsByID(ctx context.Context, id pgtype.UUID) (GetCredentialsByIDRow, error) {
	row := q.db.QueryRow(ctx, getCredentialsByID, id)
	var i GetCredentialsByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT s.id, s.user_id, s.token_hash, s.created_at, s.last_seen_at,
       s.expires_at, s.authenticated_at, s.revoked_at,
       u.password_changed_at
  FROM sessions s
  JOIN users u ON u.id = s.user_id
 WHERE s.token_hash = $1
`

type GetSessionByTokenHashRow struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	TokenHash         []byte
	CreatedAt         pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	ExpiresAt         pgtype.Timestamptz
	AuthenticatedAt   pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
	PasswordChangedAt pgtype.Timestamptz
}

// The lookup on every authenticated request.
//
// The row comes back whatever its state, and the repository decides. Three
// things end a session — expiry, revocation, and a password changed since it
// began — and they are one answer to whoever holds the cookie, so they are
// resolved in one place rather than by every caller remembering all three.
//
// Awaiting a second factor is not one of them. Such a session is returned, and
// must be: it is the credential the second step itself presents, and refusing
// it here would make completing two-factor authentication impossible.
//
// password_changed_at is joined in rather than looked up separately so the
// decision is made from one consistent read.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.AuthenticatedAt,
		&i.RevokedAt,
		&i.PasswordChangedAt,
	)
	return i, err
}

const getTOTP = `-- name: GetTOTP :one
SELECT user_id, secret, confirmed_at, last_used_counter, created_at
  FROM user_totp WHERE user_id = $1
`

func (q *Queries) GetTOTP(ctx context.Context, userID pgtype.UUID) (UserTotp, error) {
	row := q.db.QueryRow(ctx, getTOTP, userID)
	var i UserTotp
	err := row.Scan(
		&i.UserID,
		&i.Secret,
		&i.ConfirmedAt,
		&i.LastUsedCounter,
		&i.CreatedAt,
	)
	return i, err
}

const getTOTPForUpdate = `-- name: GetTOTPForUpdate :one
SELECT user_id, secret, confirmed_at, last_used_counter, created_at
  FROM user_totp WHERE user_id = $1
   FOR UPDATE
`

// The same reading, taking a row lock.
//
// Verifying a code is read-decide-write: read the highest counter already
// spent, check the code against the accepted window, write the counter it
// matched. Two submissions of the same code running at once would otherwise
// both read the old counter, both find the code unspent, and both succeed —
// which is exactly the replay the counter exists to prevent, arriving through
// the door left open by not holding the row. The lock makes the second one
// wait, re-read, and correctly refuse.
func (q *Queries) GetTOTPForUpdate(ctx context.Context, userID pgtype.UUID) (UserTotp, error) {
	row := q.db.QueryRow(ctx, getTOTPForUpdate, userID)
	var i UserTotp
	err := row.Scan(
		&i.UserID,
		&i.Secret,
		&i.ConfirmedAt,
		&i.LastUsedCounter,
		&i.CreatedAt,
	)
	return i, err
}

const insertBackupCode = `-- name: InsertBackupCode :exec

INSERT INTO user_backup_codes (user_id, code_hash, created_at)
VALUES ($1, $2, $3)
`

type InsertBackupCodeParams struct {
	UserID    pgtype.UUID
	CodeHash  string
	CreatedAt pgtype.Timestamptz
}

// ---------------------------------------------------------------------------
// Backup codes
// ---------------------------------------------------------------------------
func (q *Queries) InsertBackupCode(ctx context.Context, arg InsertBackupCodeParams) error {
	_, err := q.db.Exec(ctx, insertBackupCode, arg.UserID, arg.CodeHash, arg.CreatedAt)
	return err
}

const insertCredentialedUser = `-- name: InsertCredentialedUser :exec

INSERT INTO users (id, email, password_hash, password_changed_at, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertCredentialedUserParams struct {
	ID                pgtype.UUID
	Email             *string
	PasswordHash      *string
	PasswordChangedAt pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

// Credentials, sessions and second factors.
// Registers a person.
//
// Whether registration is open is not asked here, and deliberately so. The
// users_at_most_one_credentialed index makes a second credentialed row
// impossible, so a concurrent pair of registrations against an empty instance
// resolves in the database rather than in a check the caller could forget or
// race. The second inserter blocks on the uncommitted index entry until the
// first transaction resolves, then fails with a unique violation.
func (q *Queries) InsertCredentialedUser(ctx context.Context, arg InsertCredentialedUserParams) error {
	_, err := q.db.Exec(ctx, insertCredentialedUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.PasswordChangedAt,
		arg.CreatedAt,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec

INSERT INTO sessions (
    id, user_id, token_hash, created_at, last_seen_at, expires_at, authenticated_at
) VALUES ($1, $2, $3, $4, $4, $5, $6)
`

type InsertSessionParams struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	TokenHash       []byte
	CreatedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	AuthenticatedAt pgtype.Timestamptz
}

// ---------------------------------------------------------------------------
// Sessions
// ---------------------------------------------------------------------------
func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.AuthenticatedAt,
	)
	return err
}

const listUnusedBackupCodeHashes = `-- name: ListUnusedBackupCodeHashes :many
SELECT code_hash
  FROM user_backup_codes
 WHERE user_id = $1 AND used_at IS NULL
 ORDER BY code_hash
`

// The candidates a submitted code is matched against.
//
// No FOR UPDATE here, unlike the TOTP enrolment, and the difference is worth
// being exact about because the two problems look identical and are not.
//
// TOTP writes an unconditional `SET last_used_counter = $2`, so nothing in the
// statement itself can tell that another transaction already advanced it. The
// lock is what serialises those, and removing it lets two submissions of one
// code both succeed — established by removing it and watching the concurrency
// test go red.
//
// Spending a backup code is naturally conditional instead: the row must still
// be unspent, which MarkBackupCodeUsed states in its own WHERE. Under READ
// COMMITTED the second UPDATE blocks on the first one's row lock, re-evaluates
// its condition against the committed version, and matches nothing. A lock
// taken here would add no guarantee — established the same way, by removing it
// and watching the concurrency test stay green, which is why it is not here.
// Do not add one back believing it protects something.
//
// The `used_at IS NULL` filter is likewise not what makes a code single use; a
// spent code that reached the matcher would still fail at the UPDATE. It is
// here because it is the correct question and because it uses the partial
// index. ORDER BY makes the result deterministic for the same reason every
// other list in this file is ordered.
func (q *Queries) ListUnusedBackupCodeHashes(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUnusedBackupCodeHashes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code_hash string
		if err := rows.Scan(&code_hash); err != nil {
			return nil, err
		}
		items = append(items, code_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, user_id, token_hash, created_at, last_seen_at,
       expires_at, authenticated_at, revoked_at
  FROM sessions
 WHERE user_id = $1
 ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListUserSessions(ctx context.Context, userID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.AuthenticatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBackupCodeUsed = `-- name: MarkBackupCodeUsed :execrows
UPDATE user_backup_codes
   SET used_at = $3
 WHERE user_id = $1 AND code_hash = $2 AND used_at IS NULL
`

type MarkBackupCodeUsedParams struct {
	UserID   pgtype.UUID
	CodeHash string
	UsedAt   pgtype.Timestamptz
}

// This is the whole of the single-use guarantee.
//
// `used_at IS NULL` is not a defensive extra: it is the only thing standing
// between one code and two uses of it. Two submissions racing here both reach
// this statement, one updates a row and the other updates nothing. Remove the
// clause and a backup code becomes reusable, which the concurrency test says
// immediately.
func (q *Queries) MarkBackupCodeUsed(ctx context.Context, arg MarkBackupCodeUsedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markBackupCodeUsed, arg.UserID, arg.CodeHash, arg.UsedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions
   SET revoked_at = COALESCE(revoked_at, $1)
 WHERE id = $2
`

type RevokeSessionParams struct {
	RevokedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

// Withdrawn, never deleted: see the column comment on sessions.revoked_at.
//
// COALESCE rather than a `revoked_at IS NULL` clause, so that the row count
// means one thing only. Filtering on it in the WHERE would make an
// already-revoked session and a session that never existed both report zero
// rows, and revoking twice would then be indistinguishable from revoking
// nothing. Written this way the update is idempotent, the first revocation
// time survives a second attempt, and zero rows means exactly what it says.
func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, arg.RevokedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserSessions = `-- name: RevokeUserSessions :execrows
UPDATE sessions
   SET revoked_at = $1
 WHERE user_id = $2
   AND revoked_at IS NULL
   AND id <> $3
`

type RevokeUserSessionsParams struct {
	RevokedAt pgtype.Timestamptz
	UserID    pgtype.UUID
	ExceptID  pgtype.UUID
}

// Everything belonging to one person, optionally sparing one — which is what
// "change my password and sign out my other devices" needs.
func (q *Queries) RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserSessions, arg.RevokedAt, arg.UserID, arg.ExceptID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateSessionToken = `-- name: RotateSessionToken :execrows
UPDATE sessions
   SET token_hash = $2, authenticated_at = $3, last_seen_at = $3
 WHERE id = $1
   AND authenticated_at IS NULL
   AND revoked_at IS NULL
   AND expires_at > $3
`

type RotateSessionTokenParams struct {
	ID              pgtype.UUID
	TokenHash       []byte
	AuthenticatedAt pgtype.Timestamptz
}

// Replaces the token on a session and marks the second factor satisfied.
//
// The token changes because the privilege does. A session that is handed a
// cookie before authentication and keeps the same cookie afterwards is a
// session fixation: anything that learned the pre-authentication token holds a
// fully authenticated one the moment the person completes their second step.
//
// The WHERE clause refuses to elevate a session twice, so a replayed
// completion cannot mint a second live token for the same row.
func (q *Queries) RotateSessionToken(ctx context.Context, arg RotateSessionTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateSessionToken, arg.ID, arg.TokenHash, arg.AuthenticatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setTOTPCounter = `-- name: SetTOTPCounter :exec
UPDATE user_totp SET last_used_counter = $2 WHERE user_id = $1
`

type SetTOTPCounterParams struct {
	UserID          pgtype.UUID
	LastUsedCounter int64
}

func (q *Queries) SetTOTPCounter(ctx context.Context, arg SetTOTPCounterParams) error {
	_, err := q.db.Exec(ctx, setTOTPCounter, arg.UserID, arg.LastUsedCounter)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = $2 WHERE id = $1
`

type TouchSessionParams struct {
	ID         pgtype.UUID
	LastSeenAt pgtype.Timestamptz
}

// Records that a session was used. Separate from the lookup because a read
// should not have to be a write: the caller decides how often this is worth
// doing, and an idle-timeout policy is what will decide it.
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.LastSeenAt)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :execrows
UPDATE users
   SET password_hash = $2, password_changed_at = $3
 WHERE id = $1 AND password_hash IS NOT NULL
`

type UpdatePasswordHashParams struct {
	ID                pgtype.UUID
	PasswordHash      *string
	PasswordChangedAt pgtype.Timestamptz
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePasswordHash, arg.ID, arg.PasswordHash, arg.PasswordChangedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertTOTPEnrolment = `-- name: UpsertTOTPEnrolment :exec

INSERT INTO user_totp (user_id, secret, created_at)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
    SET secret            = excluded.secret,
        created_at        = excluded.created_at,
        confirmed_at      = NULL,
        last_used_counter = 0
`

type UpsertTOTPEnrolmentParams struct {
	UserID    pgtype.UUID
	Secret    []byte
	CreatedAt pgtype.Timestamptz
}

// ---------------------------------------------------------------------------
// TOTP
// ---------------------------------------------------------------------------
// Begins enrolment, replacing any unfinished one.
//
// Re-enrolling resets the counter to zero, and that is safe precisely because
// the secret is new: a counter only guards against a code being reused against
// the secret it was generated from, and no code exists yet for this one.
func (q *Queries) UpsertTOTPEnrolment(ctx context.Context, arg UpsertTOTPEnrolmentParams) error {
	_, err := q.db.Exec(ctx, upsertTOTPEnrolment, arg.UserID, arg.Secret, arg.CreatedAt)
	return err
}
