// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookkeeping.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :one
INSERT INTO idempotency_keys (
    actor_id, key, fingerprint, entity_kind, entity_id, created_at, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (actor_id, key) DO UPDATE
    SET fingerprint     = excluded.fingerprint,
        entity_kind     = excluded.entity_kind,
        entity_id       = excluded.entity_id,
        -- An expired claim being taken over must not keep the previous
        -- attempt's answer: the work is about to be done again, and a
        -- stale body paired with a fresh entity id would replay a
        -- response describing something that no longer exists.
        response_body   = NULL,
        response_status = NULL,
        created_at      = excluded.created_at,
        expires_at      = excluded.expires_at
  WHERE idempotency_keys.expires_at <= excluded.created_at
RETURNING actor_id, key, fingerprint, entity_kind, entity_id, response_status, response_body, created_at, expires_at
`

type ClaimIdempotencyKeyParams struct {
	ActorID     pgtype.UUID
	Key         string
	Fingerprint []byte
	EntityKind  string
	EntityID    pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

type ClaimIdempotencyKeyRow struct {
	ActorID        pgtype.UUID
	Key            string
	Fingerprint    []byte
	EntityKind     string
	EntityID       pgtype.UUID
	ResponseStatus *int16
	ResponseBody   []byte
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

// Claims a key, or reports that someone already holds a live one.
//
// No row comes back when the key is held and has not expired, which is the
// signal to read the existing claim and decide between a replay and a refusal.
// A concurrent claimer blocks here until the first transaction commits or
// aborts, so two simultaneous replays of the same write cannot both proceed.
//
// An expired claim is taken over rather than left to block forever, which is
// what makes the TTL mean something for correctness and not just for the
// sweeper.
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (ClaimIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, claimIdempotencyKey,
		arg.ActorID,
		arg.Key,
		arg.Fingerprint,
		arg.EntityKind,
		arg.EntityID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i ClaimIdempotencyKeyRow
	err := row.Scan(
		&i.ActorID,
		&i.Key,
		&i.Fingerprint,
		&i.EntityKind,
		&i.EntityID,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const countAuditEntries = `-- name: CountAuditEntries :one
SELECT count(*) FROM audit_log
`

func (q *Queries) CountAuditEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT actor_id, key, fingerprint, entity_kind, entity_id, response_status, response_body, created_at, expires_at
  FROM idempotency_keys
 WHERE actor_id = $1 AND key = $2
`

type GetIdempotencyKeyParams struct {
	ActorID pgtype.UUID
	Key     string
}

type GetIdempotencyKeyRow struct {
	ActorID        pgtype.UUID
	Key            string
	Fingerprint    []byte
	EntityKind     string
	EntityID       pgtype.UUID
	ResponseStatus *int16
	ResponseBody   []byte
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.ActorID, arg.Key)
	var i GetIdempotencyKeyRow
	err := row.Scan(
		&i.ActorID,
		&i.Key,
		&i.Fingerprint,
		&i.EntityKind,
		&i.EntityID,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getLot = `-- name: GetLot :one
SELECT id, account_id, opened_by, opened_on,
       quantity_amount, quantity_commodity,
       remaining_amount, remaining_commodity,
       cost_amount, cost_commodity
  FROM lots WHERE id = $1
`

func (q *Queries) GetLot(ctx context.Context, id pgtype.UUID) (Lot, error) {
	row := q.db.QueryRow(ctx, getLot, id)
	var i Lot
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.OpenedBy,
		&i.OpenedOn,
		&i.QuantityAmount,
		&i.QuantityCommodity,
		&i.RemainingAmount,
		&i.RemainingCommodity,
		&i.CostAmount,
		&i.CostCommodity,
	)
	return i, err
}

const insertAuditEntry = `-- name: InsertAuditEntry :exec
INSERT INTO audit_log (
    id, occurred_at, actor_id, origin, action, entity_kind, entity_id, diff
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAuditEntryParams struct {
	ID         pgtype.UUID
	OccurredAt pgtype.Timestamptz
	ActorID    pgtype.UUID
	Origin     string
	Action     string
	EntityKind string
	EntityID   pgtype.UUID
	Diff       []byte
}

func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error {
	_, err := q.db.Exec(ctx, insertAuditEntry,
		arg.ID,
		arg.OccurredAt,
		arg.ActorID,
		arg.Origin,
		arg.Action,
		arg.EntityKind,
		arg.EntityID,
		arg.Diff,
	)
	return err
}

const insertLot = `-- name: InsertLot :exec
INSERT INTO lots (
    id, account_id, opened_by, opened_on,
    quantity_amount, quantity_commodity,
    remaining_amount, remaining_commodity,
    cost_amount, cost_commodity
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertLotParams struct {
	ID                 pgtype.UUID
	AccountID          pgtype.UUID
	OpenedBy           pgtype.UUID
	OpenedOn           pgtype.Date
	QuantityAmount     pgtype.Numeric
	QuantityCommodity  string
	RemainingAmount    pgtype.Numeric
	RemainingCommodity string
	CostAmount         pgtype.Numeric
	CostCommodity      string
}

func (q *Queries) InsertLot(ctx context.Context, arg InsertLotParams) error {
	_, err := q.db.Exec(ctx, insertLot,
		arg.ID,
		arg.AccountID,
		arg.OpenedBy,
		arg.OpenedOn,
		arg.QuantityAmount,
		arg.QuantityCommodity,
		arg.RemainingAmount,
		arg.RemainingCommodity,
		arg.CostAmount,
		arg.CostCommodity,
	)
	return err
}

const insertLotConsumption = `-- name: InsertLotConsumption :exec
INSERT INTO lot_consumptions (
    posting_id, lot_id,
    quantity_amount, quantity_commodity,
    basis_num, basis_den, basis_commodity
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertLotConsumptionParams struct {
	PostingID         pgtype.UUID
	LotID             pgtype.UUID
	QuantityAmount    pgtype.Numeric
	QuantityCommodity string
	BasisNum          pgtype.Numeric
	BasisDen          pgtype.Numeric
	BasisCommodity    string
}

// One lot's part in one disposing line. Section 4.7: the basis is an exact
// fraction, never rounded on the way in.
func (q *Queries) InsertLotConsumption(ctx context.Context, arg InsertLotConsumptionParams) error {
	_, err := q.db.Exec(ctx, insertLotConsumption,
		arg.PostingID,
		arg.LotID,
		arg.QuantityAmount,
		arg.QuantityCommodity,
		arg.BasisNum,
		arg.BasisDen,
		arg.BasisCommodity,
	)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (id) VALUES ($1)
`

func (q *Queries) InsertUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, insertUser, id)
	return err
}

const listAuditEntriesForEntity = `-- name: ListAuditEntriesForEntity :many
SELECT id, occurred_at, actor_id, origin, action, entity_kind, entity_id, diff
  FROM audit_log
 WHERE entity_kind = $1 AND entity_id = $2
 ORDER BY occurred_at DESC, id DESC
`

type ListAuditEntriesForEntityParams struct {
	EntityKind string
	EntityID   pgtype.UUID
}

func (q *Queries) ListAuditEntriesForEntity(ctx context.Context, arg ListAuditEntriesForEntityParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditEntriesForEntity, arg.EntityKind, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.ActorID,
			&i.Origin,
			&i.Action,
			&i.EntityKind,
			&i.EntityID,
			&i.Diff,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsumptionsByLot = `-- name: ListConsumptionsByLot :many
SELECT posting_id, lot_id,
       quantity_amount, quantity_commodity,
       basis_num, basis_den, basis_commodity
  FROM lot_consumptions
 WHERE lot_id = $1
 ORDER BY posting_id
`

// Everything that has ever drawn on one lot. This is what reconstructs
// remaining_amount from the appended record rather than trusting the running
// figure, which is the drift check the M2a notes ask for wherever a cached
// number exists.
func (q *Queries) ListConsumptionsByLot(ctx context.Context, lotID pgtype.UUID) ([]LotConsumption, error) {
	rows, err := q.db.Query(ctx, listConsumptionsByLot, lotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LotConsumption{}
	for rows.Next() {
		var i LotConsumption
		if err := rows.Scan(
			&i.PostingID,
			&i.LotID,
			&i.QuantityAmount,
			&i.QuantityCommodity,
			&i.BasisNum,
			&i.BasisDen,
			&i.BasisCommodity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsumptionsByPosting = `-- name: ListConsumptionsByPosting :many
SELECT c.posting_id, c.lot_id,
       c.quantity_amount, c.quantity_commodity,
       c.basis_num, c.basis_den, c.basis_commodity
  FROM lot_consumptions c
  JOIN lots l ON l.id = c.lot_id
 WHERE c.posting_id = $1
 ORDER BY l.opened_on, l.id
`

// What one disposing line drew on. Ordered by the lots' own FIFO ordering, so
// a disposal reads back in the order it consumed — that order is derived from
// the lots rather than stored, because it is a trace of the selection and not
// a fact about the disposal.
func (q *Queries) ListConsumptionsByPosting(ctx context.Context, postingID pgtype.UUID) ([]LotConsumption, error) {
	rows, err := q.db.Query(ctx, listConsumptionsByPosting, postingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LotConsumption{}
	for rows.Next() {
		var i LotConsumption
		if err := rows.Scan(
			&i.PostingID,
			&i.LotID,
			&i.QuantityAmount,
			&i.QuantityCommodity,
			&i.BasisNum,
			&i.BasisDen,
			&i.BasisCommodity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenLotsByAccount = `-- name: ListOpenLotsByAccount :many
SELECT id, account_id, opened_by, opened_on,
       quantity_amount, quantity_commodity,
       remaining_amount, remaining_commodity,
       cost_amount, cost_commodity
  FROM lots
 WHERE account_id = $1 AND remaining_amount > 0
 ORDER BY opened_on, id
`

// FIFO order: oldest first, identity breaking the tie so the same disposal
// computes the same gain on every run.
func (q *Queries) ListOpenLotsByAccount(ctx context.Context, accountID pgtype.UUID) ([]Lot, error) {
	rows, err := q.db.Query(ctx, listOpenLotsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lot{}
	for rows.Next() {
		var i Lot
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.OpenedBy,
			&i.OpenedOn,
			&i.QuantityAmount,
			&i.QuantityCommodity,
			&i.RemainingAmount,
			&i.RemainingCommodity,
			&i.CostAmount,
			&i.CostCommodity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenLotsByAccountForUpdate = `-- name: ListOpenLotsByAccountForUpdate :many
SELECT id, account_id, opened_by, opened_on,
       quantity_amount, quantity_commodity,
       remaining_amount, remaining_commodity,
       cost_amount, cost_commodity
  FROM lots
 WHERE account_id = $1 AND remaining_amount > 0
 ORDER BY opened_on, id
   FOR UPDATE
`

// The same reading as ListOpenLotsByAccount, taking a row lock on every lot it
// returns.
//
// A disposal reads the open lots, decides what to consume, and writes the
// reduced figures back. Two disposals on one account running at the same time
// would otherwise both read the same lots, both find them sufficient, and both
// commit — leaving the holding consumed twice and remaining_amount describing
// neither. The lock makes the second one wait, re-read, and correctly run out
// of units.
func (q *Queries) ListOpenLotsByAccountForUpdate(ctx context.Context, accountID pgtype.UUID) ([]Lot, error) {
	rows, err := q.db.Query(ctx, listOpenLotsByAccountForUpdate, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lot{}
	for rows.Next() {
		var i Lot
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.OpenedBy,
			&i.OpenedOn,
			&i.QuantityAmount,
			&i.QuantityCommodity,
			&i.RemainingAmount,
			&i.RemainingCommodity,
			&i.CostAmount,
			&i.CostCommodity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordIdempotentResponse = `-- name: RecordIdempotentResponse :execrows
UPDATE idempotency_keys
   SET response_status = $3, response_body = $4
 WHERE actor_id = $1 AND key = $2
`

type RecordIdempotentResponseParams struct {
	ActorID        pgtype.UUID
	Key            string
	ResponseStatus *int16
	ResponseBody   []byte
}

// Stores what the first attempt answered, so a replay can repeat it.
//
// Status and body are written together because the constraint refuses half a
// response: a replay that had to invent a missing status would be answering a
// question the original never asked.
func (q *Queries) RecordIdempotentResponse(ctx context.Context, arg RecordIdempotentResponseParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordIdempotentResponse,
		arg.ActorID,
		arg.Key,
		arg.ResponseStatus,
		arg.ResponseBody,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setLotRemaining = `-- name: SetLotRemaining :exec
UPDATE lots SET remaining_amount = $2 WHERE id = $1
`

type SetLotRemainingParams struct {
	ID              pgtype.UUID
	RemainingAmount pgtype.Numeric
}

// A lot's remaining quantity is a running position rather than a record of an
// event, so it moves. What moved it is not lost: every movement appends a row
// to lot_consumptions, and summing those reconstructs this figure from scratch.
// The same relationship section 5.2 describes between a cached balance and the
// postings it comes from.
func (q *Queries) SetLotRemaining(ctx context.Context, arg SetLotRemainingParams) error {
	_, err := q.db.Exec(ctx, setLotRemaining, arg.ID, arg.RemainingAmount)
	return err
}
