// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookkeeping.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :one
INSERT INTO idempotency_keys (
    actor_id, key, fingerprint, entity_kind, entity_id, created_at, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (actor_id, key) DO UPDATE
    SET fingerprint = excluded.fingerprint,
        entity_kind = excluded.entity_kind,
        entity_id   = excluded.entity_id,
        response    = NULL,
        created_at  = excluded.created_at,
        expires_at  = excluded.expires_at
  WHERE idempotency_keys.expires_at <= excluded.created_at
RETURNING actor_id, key, fingerprint, entity_kind, entity_id, response, created_at, expires_at
`

type ClaimIdempotencyKeyParams struct {
	ActorID     pgtype.UUID
	Key         string
	Fingerprint []byte
	EntityKind  string
	EntityID    pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

// Claims a key, or reports that someone already holds a live one.
//
// No row comes back when the key is held and has not expired, which is the
// signal to read the existing claim and decide between a replay and a refusal.
// A concurrent claimer blocks here until the first transaction commits or
// aborts, so two simultaneous replays of the same write cannot both proceed.
//
// An expired claim is taken over rather than left to block forever, which is
// what makes the TTL mean something for correctness and not just for the
// sweeper.
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, claimIdempotencyKey,
		arg.ActorID,
		arg.Key,
		arg.Fingerprint,
		arg.EntityKind,
		arg.EntityID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ActorID,
		&i.Key,
		&i.Fingerprint,
		&i.EntityKind,
		&i.EntityID,
		&i.Response,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const countAuditEntries = `-- name: CountAuditEntries :one
SELECT count(*) FROM audit_log
`

func (q *Queries) CountAuditEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT actor_id, key, fingerprint, entity_kind, entity_id, response, created_at, expires_at
  FROM idempotency_keys
 WHERE actor_id = $1 AND key = $2
`

type GetIdempotencyKeyParams struct {
	ActorID pgtype.UUID
	Key     string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.ActorID, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.ActorID,
		&i.Key,
		&i.Fingerprint,
		&i.EntityKind,
		&i.EntityID,
		&i.Response,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getLot = `-- name: GetLot :one
SELECT id, account_id, opened_by, opened_on,
       quantity_amount, quantity_commodity,
       remaining_amount, remaining_commodity,
       cost_amount, cost_commodity
  FROM lots WHERE id = $1
`

func (q *Queries) GetLot(ctx context.Context, id pgtype.UUID) (Lot, error) {
	row := q.db.QueryRow(ctx, getLot, id)
	var i Lot
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.OpenedBy,
		&i.OpenedOn,
		&i.QuantityAmount,
		&i.QuantityCommodity,
		&i.RemainingAmount,
		&i.RemainingCommodity,
		&i.CostAmount,
		&i.CostCommodity,
	)
	return i, err
}

const insertAuditEntry = `-- name: InsertAuditEntry :exec
INSERT INTO audit_log (
    id, occurred_at, actor_id, origin, action, entity_kind, entity_id, diff
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAuditEntryParams struct {
	ID         pgtype.UUID
	OccurredAt pgtype.Timestamptz
	ActorID    pgtype.UUID
	Origin     string
	Action     string
	EntityKind string
	EntityID   pgtype.UUID
	Diff       []byte
}

func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error {
	_, err := q.db.Exec(ctx, insertAuditEntry,
		arg.ID,
		arg.OccurredAt,
		arg.ActorID,
		arg.Origin,
		arg.Action,
		arg.EntityKind,
		arg.EntityID,
		arg.Diff,
	)
	return err
}

const insertLot = `-- name: InsertLot :exec
INSERT INTO lots (
    id, account_id, opened_by, opened_on,
    quantity_amount, quantity_commodity,
    remaining_amount, remaining_commodity,
    cost_amount, cost_commodity
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertLotParams struct {
	ID                 pgtype.UUID
	AccountID          pgtype.UUID
	OpenedBy           pgtype.UUID
	OpenedOn           pgtype.Date
	QuantityAmount     pgtype.Numeric
	QuantityCommodity  string
	RemainingAmount    pgtype.Numeric
	RemainingCommodity string
	CostAmount         pgtype.Numeric
	CostCommodity      string
}

func (q *Queries) InsertLot(ctx context.Context, arg InsertLotParams) error {
	_, err := q.db.Exec(ctx, insertLot,
		arg.ID,
		arg.AccountID,
		arg.OpenedBy,
		arg.OpenedOn,
		arg.QuantityAmount,
		arg.QuantityCommodity,
		arg.RemainingAmount,
		arg.RemainingCommodity,
		arg.CostAmount,
		arg.CostCommodity,
	)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (id) VALUES ($1)
`

func (q *Queries) InsertUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, insertUser, id)
	return err
}

const listAuditEntriesForEntity = `-- name: ListAuditEntriesForEntity :many
SELECT id, occurred_at, actor_id, origin, action, entity_kind, entity_id, diff
  FROM audit_log
 WHERE entity_kind = $1 AND entity_id = $2
 ORDER BY occurred_at DESC, id DESC
`

type ListAuditEntriesForEntityParams struct {
	EntityKind string
	EntityID   pgtype.UUID
}

func (q *Queries) ListAuditEntriesForEntity(ctx context.Context, arg ListAuditEntriesForEntityParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditEntriesForEntity, arg.EntityKind, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.ActorID,
			&i.Origin,
			&i.Action,
			&i.EntityKind,
			&i.EntityID,
			&i.Diff,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenLotsByAccount = `-- name: ListOpenLotsByAccount :many
SELECT id, account_id, opened_by, opened_on,
       quantity_amount, quantity_commodity,
       remaining_amount, remaining_commodity,
       cost_amount, cost_commodity
  FROM lots
 WHERE account_id = $1 AND remaining_amount > 0
 ORDER BY opened_on, id
`

// FIFO order: oldest first, identity breaking the tie so the same disposal
// computes the same gain on every run.
func (q *Queries) ListOpenLotsByAccount(ctx context.Context, accountID pgtype.UUID) ([]Lot, error) {
	rows, err := q.db.Query(ctx, listOpenLotsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lot{}
	for rows.Next() {
		var i Lot
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.OpenedBy,
			&i.OpenedOn,
			&i.QuantityAmount,
			&i.QuantityCommodity,
			&i.RemainingAmount,
			&i.RemainingCommodity,
			&i.CostAmount,
			&i.CostCommodity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLotRemaining = `-- name: SetLotRemaining :exec
UPDATE lots SET remaining_amount = $2 WHERE id = $1
`

type SetLotRemainingParams struct {
	ID              pgtype.UUID
	RemainingAmount pgtype.Numeric
}

// The one mutable figure in the schema, and it is not history: a lot's
// remaining quantity is a running position, not a record of an event. What
// consumed it is recorded by the disposal transaction.
func (q *Queries) SetLotRemaining(ctx context.Context, arg SetLotRemainingParams) error {
	_, err := q.db.Exec(ctx, setLotRemaining, arg.ID, arg.RemainingAmount)
	return err
}
