// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commodities.sql

package store

import (
	"context"
)

const getCommodity = `-- name: GetCommodity :one
SELECT code, kind, scale FROM commodities WHERE code = $1
`

func (q *Queries) GetCommodity(ctx context.Context, code string) (Commodity, error) {
	row := q.db.QueryRow(ctx, getCommodity, code)
	var i Commodity
	err := row.Scan(&i.Code, &i.Kind, &i.Scale)
	return i, err
}

const listCommodities = `-- name: ListCommodities :many
SELECT code, kind, scale FROM commodities ORDER BY code
`

// Every commodity this instance knows, core plus whatever Country Packs added.
func (q *Queries) ListCommodities(ctx context.Context) ([]Commodity, error) {
	rows, err := q.db.Query(ctx, listCommodities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Commodity{}
	for rows.Next() {
		var i Commodity
		if err := rows.Scan(&i.Code, &i.Kind, &i.Scale); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCommodity = `-- name: UpsertCommodity :exec
INSERT INTO commodities (code, kind, scale)
VALUES ($1, $2, $3)
ON CONFLICT (code) DO UPDATE
    SET kind = excluded.kind
  WHERE commodities.kind = excluded.kind
    AND commodities.scale = excluded.scale
`

type UpsertCommodityParams struct {
	Code  string
	Kind  string
	Scale int16
}

// Country Packs register their own securities and funds. A redefinition that
// disagrees with what is already stored is refused rather than silently
// applied: a commodity whose scale changes underneath stored amounts would
// move every decimal point already written.
func (q *Queries) UpsertCommodity(ctx context.Context, arg UpsertCommodityParams) error {
	_, err := q.db.Exec(ctx, upsertCommodity, arg.Code, arg.Kind, arg.Scale)
	return err
}
