// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: journal.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accountBalance = `-- name: AccountBalance :many

SELECT commodity_code, sum(amount)::numeric AS total
  FROM postings
 WHERE account_id = $1
 GROUP BY commodity_code
 ORDER BY commodity_code
`

type AccountBalanceRow struct {
	CommodityCode string
	Total         pgtype.Numeric
}

// The balance queries below are the whole of CLAUDE.md 5.2 as it reaches the
// database: an account balance is the sum of its postings and nothing else.
// There is no cached figure anywhere to drift from them.
//
// All-time and as-of are separate statements rather than one query with an
// optional date, because a nullable predicate (date IS NULL OR txn_date <= date)
// is not sargable and would cost the index-only scan both of them depend on.
func (q *Queries) AccountBalance(ctx context.Context, accountID pgtype.UUID) ([]AccountBalanceRow, error) {
	rows, err := q.db.Query(ctx, accountBalance, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountBalanceRow{}
	for rows.Next() {
		var i AccountBalanceRow
		if err := rows.Scan(&i.CommodityCode, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountBalanceAsOf = `-- name: AccountBalanceAsOf :many
SELECT commodity_code, sum(amount)::numeric AS total
  FROM postings
 WHERE account_id = $1 AND txn_date <= $2
 GROUP BY commodity_code
 ORDER BY commodity_code
`

type AccountBalanceAsOfParams struct {
	AccountID pgtype.UUID
	TxnDate   pgtype.Date
}

type AccountBalanceAsOfRow struct {
	CommodityCode string
	Total         pgtype.Numeric
}

func (q *Queries) AccountBalanceAsOf(ctx context.Context, arg AccountBalanceAsOfParams) ([]AccountBalanceAsOfRow, error) {
	rows, err := q.db.Query(ctx, accountBalanceAsOf, arg.AccountID, arg.TxnDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountBalanceAsOfRow{}
	for rows.Next() {
		var i AccountBalanceAsOfRow
		if err := rows.Scan(&i.CommodityCode, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountBalanceBetween = `-- name: AccountBalanceBetween :many
SELECT commodity_code, sum(amount)::numeric AS total
  FROM postings
 WHERE account_id = $1 AND txn_date >= $2 AND txn_date <= $3
 GROUP BY commodity_code
 ORDER BY commodity_code
`

type AccountBalanceBetweenParams struct {
	AccountID pgtype.UUID
	TxnDate   pgtype.Date
	TxnDate_2 pgtype.Date
}

type AccountBalanceBetweenRow struct {
	CommodityCode string
	Total         pgtype.Numeric
}

func (q *Queries) AccountBalanceBetween(ctx context.Context, arg AccountBalanceBetweenParams) ([]AccountBalanceBetweenRow, error) {
	rows, err := q.db.Query(ctx, accountBalanceBetween, arg.AccountID, arg.TxnDate, arg.TxnDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountBalanceBetweenRow{}
	for rows.Next() {
		var i AccountBalanceBetweenRow
		if err := rows.Scan(&i.CommodityCode, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTransactions = `-- name: CountTransactions :one
SELECT count(*) FROM transactions
`

func (q *Queries) CountTransactions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPostingOwner = `-- name: GetPostingOwner :one
SELECT transaction_id FROM postings WHERE id = $1
`

// Widens a posting back to its transaction, which is how a lot recovers the
// transaction that opened it.
func (q *Queries) GetPostingOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getPostingOwner, id)
	var transaction_id pgtype.UUID
	err := row.Scan(&transaction_id)
	return transaction_id, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, txn_date, occurred_at, timezone, payee, memo, reverses_id, reversal_kind
  FROM transactions WHERE id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TxnDate,
		&i.OccurredAt,
		&i.Timezone,
		&i.Payee,
		&i.Memo,
		&i.ReversesID,
		&i.ReversalKind,
	)
	return i, err
}

const insertPosting = `-- name: InsertPosting :exec
INSERT INTO postings (
    id, transaction_id, txn_date, ordinal, account_id, amount, commodity_code,
    rate_base, rate_quote, rate_num, rate_den, memo, reverses_posting_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertPostingParams struct {
	ID                pgtype.UUID
	TransactionID     pgtype.UUID
	TxnDate           pgtype.Date
	Ordinal           int16
	AccountID         pgtype.UUID
	Amount            pgtype.Numeric
	CommodityCode     string
	RateBase          *string
	RateQuote         *string
	RateNum           pgtype.Numeric
	RateDen           pgtype.Numeric
	Memo              string
	ReversesPostingID pgtype.UUID
}

func (q *Queries) InsertPosting(ctx context.Context, arg InsertPostingParams) error {
	_, err := q.db.Exec(ctx, insertPosting,
		arg.ID,
		arg.TransactionID,
		arg.TxnDate,
		arg.Ordinal,
		arg.AccountID,
		arg.Amount,
		arg.CommodityCode,
		arg.RateBase,
		arg.RateQuote,
		arg.RateNum,
		arg.RateDen,
		arg.Memo,
		arg.ReversesPostingID,
	)
	return err
}

const insertTransaction = `-- name: InsertTransaction :exec
INSERT INTO transactions (
    id, txn_date, occurred_at, timezone, payee, memo, reverses_id, reversal_kind
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertTransactionParams struct {
	ID           pgtype.UUID
	TxnDate      pgtype.Date
	OccurredAt   pgtype.Timestamptz
	Timezone     string
	Payee        string
	Memo         string
	ReversesID   pgtype.UUID
	ReversalKind *string
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) error {
	_, err := q.db.Exec(ctx, insertTransaction,
		arg.ID,
		arg.TxnDate,
		arg.OccurredAt,
		arg.Timezone,
		arg.Payee,
		arg.Memo,
		arg.ReversesID,
		arg.ReversalKind,
	)
	return err
}

const listPostingsByTransaction = `-- name: ListPostingsByTransaction :many
SELECT id, transaction_id, txn_date, ordinal, account_id, amount, commodity_code,
       rate_base, rate_quote, rate_num, rate_den, memo, reverses_posting_id
  FROM postings
 WHERE transaction_id = $1
 ORDER BY ordinal
`

// Ordered by the ordinal the author wrote, which is the whole reason that
// column exists. Served by the same unique index that enforces it.
func (q *Queries) ListPostingsByTransaction(ctx context.Context, transactionID pgtype.UUID) ([]Posting, error) {
	rows, err := q.db.Query(ctx, listPostingsByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Posting{}
	for rows.Next() {
		var i Posting
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.TxnDate,
			&i.Ordinal,
			&i.AccountID,
			&i.Amount,
			&i.CommodityCode,
			&i.RateBase,
			&i.RateQuote,
			&i.RateNum,
			&i.RateDen,
			&i.Memo,
			&i.ReversesPostingID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsBetween = `-- name: ListTransactionsBetween :many
SELECT id, txn_date, occurred_at, timezone, payee, memo, reverses_id, reversal_kind
  FROM transactions
 WHERE txn_date >= $1 AND txn_date <= $2
 ORDER BY txn_date, id
`

type ListTransactionsBetweenParams struct {
	TxnDate   pgtype.Date
	TxnDate_2 pgtype.Date
}

// Civil dates, both counted. Only txn_date decides; occurred_at is never
// consulted, so the answer is the same for every reader in every zone.
func (q *Queries) ListTransactionsBetween(ctx context.Context, arg ListTransactionsBetweenParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsBetween, arg.TxnDate, arg.TxnDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.TxnDate,
			&i.OccurredAt,
			&i.Timezone,
			&i.Payee,
			&i.Memo,
			&i.ReversesID,
			&i.ReversalKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subtreeBalanceAsOf = `-- name: SubtreeBalanceAsOf :many
WITH RECURSIVE subtree(id) AS (
    SELECT a.id FROM accounts a WHERE a.id = $1
    UNION ALL
    SELECT a.id FROM accounts a JOIN subtree s ON a.parent_id = s.id
)
SELECT p.commodity_code, sum(p.amount)::numeric AS total
  FROM postings p
 WHERE p.account_id IN (SELECT s.id FROM subtree s)
   AND p.txn_date <= $2
 GROUP BY p.commodity_code
 ORDER BY p.commodity_code
`

type SubtreeBalanceAsOfParams struct {
	ID      pgtype.UUID
	TxnDate pgtype.Date
}

type SubtreeBalanceAsOfRow struct {
	CommodityCode string
	Total         pgtype.Numeric
}

func (q *Queries) SubtreeBalanceAsOf(ctx context.Context, arg SubtreeBalanceAsOfParams) ([]SubtreeBalanceAsOfRow, error) {
	rows, err := q.db.Query(ctx, subtreeBalanceAsOf, arg.ID, arg.TxnDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubtreeBalanceAsOfRow{}
	for rows.Next() {
		var i SubtreeBalanceAsOfRow
		if err := rows.Scan(&i.CommodityCode, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalsByCommodity = `-- name: TotalsByCommodity :many
SELECT commodity_code, sum(amount)::numeric AS total
  FROM postings
 GROUP BY commodity_code
 ORDER BY commodity_code
`

type TotalsByCommodityRow struct {
	CommodityCode string
	Total         pgtype.Numeric
}

// The whole-book form of 5.1. It must always be zero: each transaction sums to
// zero on its own, so any number of them still do. A non-zero total means
// something got in without passing NewTransaction.
func (q *Queries) TotalsByCommodity(ctx context.Context) ([]TotalsByCommodityRow, error) {
	rows, err := q.db.Query(ctx, totalsByCommodity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TotalsByCommodityRow{}
	for rows.Next() {
		var i TotalsByCommodityRow
		if err := rows.Scan(&i.CommodityCode, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
