// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Schema generation for this database. Exactly one row, enforced by the singleton primary key.
type SchemaMetum struct {
	Singleton bool
	Version   int32
	AppliedAt pgtype.Timestamptz
}
