// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	// Reads the schema generation. Doubles as the health endpoint's proof that the
	// connection works and that migrations have been applied.
	GetSchemaVersion(ctx context.Context) (int32, error)
}

var _ Querier = (*Queries)(nil)
