// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schema_meta.sql

package store

import (
	"context"
)

const getSchemaVersion = `-- name: GetSchemaVersion :one
SELECT version FROM schema_meta WHERE singleton
`

// Reads the schema generation. Doubles as the health endpoint's proof that the
// connection works and that migrations have been applied.
func (q *Queries) GetSchemaVersion(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getSchemaVersion)
	var version int32
	err := row.Scan(&version)
	return version, err
}
